### ISSUE TITLE
Form broken

### ISSUE THREAD

**Issue by dereuromark** [tranfuga25s/inmobiliariabarbier#156]
Sry, I tried to write you an email
http://www.gestotux.com.ar/contacto/formulario
is broken though - Exception thrown and no email sent.

PS: So you are interested in reviving the webtestrunner for Cake3?
Drop me a line
Mark

**Comment by tranfuga25s** [comment]
I haven't touched Cake3 yet... but interested in doing so... Haven't found the time to read about it...

My main concern is that the time that I can spend on reviving the webtesturunner is not very much... with a child incoming this month and my carrer to be completed and working at the same time there is not much left...
But if the plugin is not a high priority I think can help with it.

Any directions where  can find information about the testing in Cake3 or plans?

BTW, Any idea when can find any core members in the IRC channel?, been in Argentina get's complicated with the time.... and when I do it, it's like a desert.. :cactus:

**Comment by tranfuga25s** [comment]
The form gives error in the captcha... don't know if the version of recapta still's working... :(

**Comment by tranfuga25s** [comment]
Closed by moving it to the correct repository.
