### ISSUE TITLE
Agregar una sección INTERNACIONAL

### ISSUE THREAD

**Issue by daniels591** [tranfuga25s/inmobiliariabarbier#159]

**Comment by tranfuga25s** [comment]
Si agregamos un item más en la cabecera de la página, no van a entrar todos.

¿Eliminamos algún item?

**Comment by daniels591** [comment]
Tendriamos que sacar el quienes somos

**Comment by tranfuga25s** [comment]
¿Que contenido debería de tener la sección internacional?

Supongo que deberá ser el listado de propiedades según pais, que no sean de argentina. ¿O depende del idioma elegido?

**Comment by daniels591** [comment]
Listado que no sean de Argentina, sin importar el idioma

**Comment by tranfuga25s** [comment]
![screenshot-trafu no-ip org 2015-04-06 20-21-53](https://cloud.githubusercontent.com/assets/2207063/7014399/c62a72bc-dc9a-11e4-9a1e-7cc44ae067c0.png)
algo así para la sección internacional?

**Comment by daniels591** [comment]
Si me gusta solo tendría que cambiar la posición del menu deberia ser 

inicio alquileres ventas internacional contacto

**Comment by tranfuga25s** [comment]
![screenshot-trafu no-ip org 2015-04-12 12-37-38](https://cloud.githubusercontent.com/assets/2207063/7106240/d08d2702-e110-11e4-9989-bfe3ef840105.png)
Con bandera incluida

**Comment by tranfuga25s** [comment]
![screenshot-trafu no-ip org 2015-04-26 12-52-20](https://cloud.githubusercontent.com/assets/2207063/7337966/331b487e-ec13-11e4-9717-34129d5a17f7.png)
