### ISSUE TITLE
Agregar propiedad - Cocheras 

### ISSUE THREAD

**Issue by daniels591** [tranfuga25s/inmobiliariabarbier#161]
Sacar campo ¨input-mini¨

![error cocheras](https://cloud.githubusercontent.com/assets/4596315/5656537/f68c129a-96bc-11e4-951b-1ae5b5a0547b.jpg)

**Comment by tranfuga25s** [comment]
Sacar el campo es:
- Eliminarlo  y que no se vea?
- Cambiarle la clase para que sea mas grande?
- Moverlo a otra posición?
@daniels591
