### ISSUE TITLE
Ver propiedad - no muesta el campo Sup Cubierta cuando esta agregado el dato

### ISSUE THREAD

**Issue by daniels591** [tranfuga25s/inmobiliariabarbier#167]
![falta campo sup cubierta](https://cloud.githubusercontent.com/assets/4596315/5695881/eb9404e4-9994-11e4-8d31-2b2462e4b38d.png)

**Comment by tranfuga25s** [comment]
Propiedad de ejemplo?

**Comment by daniels591** [comment]
Chequeado en 2 propiedades y se muestra correctamente
