### ISSUE TITLE
Administrador - Nuevo listado

### ISSUE THREAD

**Issue by daniels591** [tranfuga25s/inmobiliariabarbier#169]
Colocar otro botón que diga "Imprimir listado completo"

# / Dirección / Precio / Tipo / Zona / Descripción / Estado

"Zona" se puede saca sino entran tantos datos.

![ejemplo1](https://cloud.githubusercontent.com/assets/4596315/6260949/afc368fc-b7c5-11e4-9b5e-53895fb73801.png)

**Comment by tranfuga25s** [comment]
Cual diferencia habría con el listado x impresión ahora?

**Comment by daniels591** [comment]
El actual contiene los siguientes campos 

# 	Direccion 	Precio 	Tipo 	Zona 	Imag. 	Estado

Necesitan uno con estos

Dirección / Precio / Tipo / Zona / Descripción / Estado
