### ISSUE TITLE
Administrador - columna "Estado"

### ISSUE THREAD

**Issue by daniels591** [tranfuga25s/inmobiliariabarbier#170]
Debajo de publicado/ no publicado tenga una opción que permita poner reservado/vendido, seria bueno ponerle un color amarillo para reservado y rojo para vendido.

![ejemplo2](https://cloud.githubusercontent.com/assets/4596315/6261024/34fb031c-b7c7-11e4-920b-aa547271e5b3.jpg)

**Comment by tranfuga25s** [comment]
¿Quienes pueden cambiar esta preferencia de la propiedad?

**Comment by tranfuga25s** [comment]
¿Se deja algúna información extra cudno se reserva una propiedad?

**Comment by daniels591** [comment]
Colaborador / Administradores

Si necesitan dejar info extra tienen la parte de notas

**Comment by tranfuga25s** [comment]
¿Se debe eliminar de las busquedas y mostrdo del fontend al estar reservada o vendida/alquilada?

**Comment by daniels591** [comment]
Calculo que no despues la desactivaran

**Comment by tranfuga25s** [comment]
ok, agregá un nuevo ticket para eso entonces.

**Comment by tranfuga25s** [comment]
![etiquetas-propiedad](https://cloud.githubusercontent.com/assets/2207063/6337551/2e24d944-bb89-11e4-976e-442461a60437.png)

**Comment by daniels591** [comment]
Si de 10 !

**Comment by daniels591** [comment]
Menu ACCIONES colocar
reservado - alquilado - vendido (esos nombres)

alquilado en colocar amarillo y vendido en color rojo

Sacar no es necesario que aparezca en el add y edit

**Comment by tranfuga25s** [comment]
Cambios subidos.

**Comment by daniels591** [comment]
Al aplicar algun estado tanto como usuario administrador o colaborador sale el siguiente error

![error](https://cloud.githubusercontent.com/assets/4596315/6405494/ca1cc3f4-be02-11e4-9548-7a2a253b872e.png)

**Comment by tranfuga25s** [comment]
Se arregó ese problema y el problema de los colores y el problema de la actualización de datos del listado despues de cambiar un reservado/alquilado/vendido

**Comment by daniels591** [comment]
Estado "Reservado" colocar un verde diferente a "Publicado"
