### ISSUE TITLE
Agregar - Últimas Propiedades

### ISSUE THREAD

**Issue by daniels591** [tranfuga25s/inmobiliariabarbier#180]
Agregar en alguna parte a libre elección una seccion donde muestre las ultimas propiedades.

Ejemplo

![agregar](https://cloud.githubusercontent.com/assets/4596315/7586872/bdfc0d68-f887-11e4-962d-74558a259515.jpg)

**Comment by tranfuga25s** [comment]
Que tiene que contener ese módulo?
Las últimas propiedades listadas con datos mínimos como está en la administración?

**Comment by daniels591** [comment]
Nombre y imagen, pero si la idea es poner datos minimo y que se muestren las ultimas 3, 4 o 5 agregadas

**Comment by tranfuga25s** [comment]
![screenshot-trafu no-ip org 2015-05-17 17-36-48](https://cloud.githubusercontent.com/assets/2207063/7672067/6d1b6e42-fcbb-11e4-8872-a4e42a5bb4c3.png)
¿Algo así? o con más info?

**Comment by tranfuga25s** [comment]
![screenshot-trafu no-ip org 2015-05-17 17-53-36](https://cloud.githubusercontent.com/assets/2207063/7672138/b248be50-fcbd-11e4-852a-df4f31ee109b.png)

**Comment by daniels591** [comment]
Muy bueno asi como esta, solo agregaria si es posible si trata de una VENTA o ALQUILER

**Comment by tranfuga25s** [comment]
![etiquetas-propiedad2](https://cloud.githubusercontent.com/assets/2207063/7788332/be0ad878-020c-11e5-8973-0be46bf79a68.png)
