### ISSUE TITLE
Administrador - permitir agregar decimales

### ISSUE THREAD

**Issue by daniels591** [tranfuga25s/inmobiliariabarbier#195]
Solo se puede poner numero enteros

![correguir](https://cloud.githubusercontent.com/assets/4596315/8098781/a457a9b2-0fca-11e5-85da-d8917fd41ca1.png)

**Comment by tranfuga25s** [comment]
¿Como? Solo te deja poner números enteros pero tiene la mascara de decimales?

**Comment by daniels591** [comment]
Exacto como lo describis
