### ISSUE TITLE
Administrador - achicar la fuente para que entre todo

### ISSUE THREAD

**Issue by daniels591** [tranfuga25s/inmobiliariabarbier#200]
![achicar fuente](https://cloud.githubusercontent.com/assets/4596315/8142251/350f3a3c-114d-11e5-8b0a-c63832e3608d.png)

**Comment by tranfuga25s** [comment]
Si te lo divido en 2 lineas de 3 elementos c/u no te parece mejor?

**Comment by daniels591** [comment]
me parece que le va gustar mas todo en 1 linea y mas chico
